version: '3.8'
services:
  jwt:
    image: zar4za/jwtservice
    ports:
      - "5001:80"
  events:
    build: 
      context: .
      dockerfile: SenseEvents/Dockerfile
    depends_on:
      - mongo
      - rabbit
    environment:
      - "Mongo:ConnectionString=mongodb://root:foobar@mongo:27017"
      - "Services:ApiToken=testtoken"
      - "Services:ImageServiceUrl=http://images:6000/api/images"
      - "Services:SpaceServiceUrl=http://spaces:6000/api/spaces"
      - "Services:PaymentsServiceUrl=http://payments:6000/api/payments"
      - "RabbitMQ:Host=rabbit"
    ports:
      - "8080:6000"
    links:
      - "images:images"
      - "spaces:spaces"
      - "payments:payments"
      - "rabbit:rabbit"
  images:
    build:
      context: .
      dockerfile: ImageService/Dockerfile
    ports:
      - "5002:6000"
  spaces:
    build:
      context: .
      dockerfile: SpaceService/Dockerfile
    ports:
      - "5003:6000"
  payments:
    build: 
      context: .
      dockerfile: PaymentsService/Dockerfile
    ports:
      - "5004:6000"
  rabbit: 
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo:6.0.5
    environment:            
      - MONGO_INITDB_ROOT_USERNAME=root            
      - MONGO_INITDB_ROOT_PASSWORD=foobar        
    ports:
      - "27017:27017"
    restart: always